name: magic_ext_oauth
description: A Magic oauth extension to support Magic social login authentication
version: 0.4.8
homepage: https://magic.link
repository: https://github.com/magiclabs/magic-flutter
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  magic_sdk:
   path: "../../magic_sdk"
  package_info_plus: ^8.2.1
  uri: ^1.0.0
  crypto: ^3.0.1
  json_annotation: ^4.5.0
  flutter_web_auth_2: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter: {}
